#################USERS##################
User.create(first_name: 'Jon', last_name: 'apple', username: 'donboy')
User.create(first_name: 'Quinn', last_name: 'Vox', username: 'Voxboy')
User.create(first_name: 'Abe', last_name: 'dude', username: 'abeboy')
User.create(first_name: 'Doug', last_name: 'wort', username: 'Dougboy')
User.create(first_name: 'Mera', last_name: 'French', username: 'paris')
User.create(first_name: 'Joe', last_name: 'Jojo', username: 'jojo')
User.create(first_name: 'Rylan', last_name: 'Merb', username: 'seadude')


#################POSTS##################
Post.create(title: "Love hikes", description: "I really love hikes a lot", user_id: 1)
Post.create(title: "Hate hikes", description: "I really hate hikes a lot", user_id: 2)
Post.create(title: "Love ocean", description: "I really love oceans a lot", user_id: 3)
Post.create(title: "Hate ocean", description: "I really hate oceans a lot", user_id: 4)
Post.create(title: "Love woods", description: "I really love woods a lot", user_id: 5)
Post.create(title: "Hate woods", description: "I really hate woods a lot", user_id: 6)
Post.create(title: "Love climb", description: "I really love climbing a lot", user_id: 7)
Post.create(title: "Hate climb", description: "I really hate climbing a lot", user_id: 1)
Post.create(title: "Road trip", description: "Road trip around the whole USA.  wow!", user_id: 2)


#################TRIPS##################
Trip.create(title: "Cascades", rating: 5, content: "great hiking with friends.", date: "October", region: "North", user_id: 1)
Trip.create(title: "Rainier", rating: 4, content: "Almost made it to the top. Big giant ice walls", date: "October", region: "Rainier", user_id: 2)
Trip.create(title: "Wine Tour", rating: 3, content: "We only drank a little wine", date: "April", region: "Bellingham", user_id: 3)
Trip.create(title: "Boat trip", rating: 4, content: "The water was cold but it was fun", date: "May", region: "Puget Sound", user_id: 4)
Trip.create(title: "Whale watch", rating: 5, content: "We saw a bajillion merbs", date: "June", region: "South", user_id: 5)
Trip.create(title: "Victoria", rating: 2, content: "SO nice being in Canada, eh!", date: "July", region: "North", user_id: 6)
Trip.create(title: "River adventure", rating: 1, content: "There was no water", date: "November", region: "Central", user_id: 7)

#################COMMENTS###############
Comment.create(content: "v good", user_id: 2, commentable_type: "Post", commentable_id: 1)
Comment.create(content: "will read again", user_id: 3, commentable_type: "Post", commentable_id: 2)
Comment.create(content: "i will share this with friends", user_id: 4, commentable_type: "Post", commentable_id: 3)
Comment.create(content: "g2g", user_id: 5, commentable_type: "Post", commentable_id: 4)
Comment.create(content: "you should sign up for my app.  It is better", user_id: 6, commentable_type: "Post", commentable_id: 5)
Comment.create(content: "idk this seems weird", user_id: 7, commentable_type: "Post", commentable_id: 6)
Comment.create(content: "I am a comment troll", user_id: 2, commentable_type: "Post", commentable_id: 7)
Comment.create(content: "want to go here", user_id: 3, commentable_type: "Trip", commentable_id: 1)
Comment.create(content: "terrible idea", user_id: 4, commentable_type: "Trip", commentable_id: 2)
Comment.create(content: "bro, do you even know the PNW", user_id: 1, commentable_type: "Trip", commentable_id: 3)
Comment.create(content: "I really like this.  Can I come?", user_id: 6, commentable_type: "Trip", commentable_id: 4)
Comment.create(content: "Your rating is wrong", user_id: 7, commentable_type: "Trip", commentable_id: 5)
Comment.create(content: "love love love love", user_id: 3, commentable_type: "Trip", commentable_id: 6)
Comment.create(content: "I wish I were there", user_id: 4, commentable_type: "Trip", commentable_id: 7)
Comment.create(content: "thumbs up", user_id: 5, commentable_type: "Trip", commentable_id: 1)
Comment.create(content: "thumbs down", user_id: 6, commentable_type: "Trip", commentable_id: 2)
Comment.create(content: "ya ya ya ya", user_id: 7, commentable_type: "Post", commentable_id: 3)
Comment.create(content: "stopppppp selling your app here.", user_id: 1, commentable_type: "Post", commentable_id: 5)

###############RELATIONSHIPS################
Relationship.create(follower_id: 1, followed_id: 2)
Relationship.create(follower_id: 2, followed_id: 3)
Relationship.create(follower_id: 3, followed_id: 4)
Relationship.create(follower_id: 4, followed_id: 5)
Relationship.create(follower_id: 5, followed_id: 6)
Relationship.create(follower_id: 6, followed_id: 7)
Relationship.create(follower_id: 7, followed_id: 1)
Relationship.create(follower_id: 1, followed_id: 3)
Relationship.create(follower_id: 2, followed_id: 4)
Relationship.create(follower_id: 2, followed_id: 4)
Relationship.create(follower_id: 3, followed_id: 5)
Relationship.create(follower_id: 4, followed_id: 6)
Relationship.create(follower_id: 4, followed_id: 1)
Relationship.create(follower_id: 5, followed_id: 7)
Relationship.create(follower_id: 5, followed_id: 1)
Relationship.create(follower_id: 5, followed_id: 2)
Relationship.create(follower_id: 5, followed_id: 3)
Relationship.create(follower_id: 6, followed_id: 3)
Relationship.create(follower_id: 6, followed_id: 4)
Relationship.create(follower_id: 1, followed_id: 4)
Relationship.create(follower_id: 1, followed_id: 6)
Relationship.create(follower_id: 1, followed_id: 7)
